<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DeterminingControlSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('determining_controls')->insert([
            [
                'risk_assessment_id' => 1,
                'risk_control' => 'Penggunaan alat bantu angkat.',
                'control_hierarchical_id' => 2,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 1,
                'risk_control' => 'Pelatihan teknik mengangkat yang benar.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 2,
                'risk_control' => 'Inspeksi kualitas rotan sebelum digunakan.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 2,
                'risk_control' => 'Penggunaan sarung tangan pelindung.',
                'control_hierarchical_id' => 5,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 3,
                'risk_control' => 'Pelindung pada pisau atau alat pemotong.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 3,
                'risk_control' => 'Pelatihan penggunaan alat pemotong yang aman.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 4,
                'risk_control' => 'Pengurangan tekanan saat memotong untuk mencegah serpihan.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 4,
                'risk_control' => 'Penggunaan kacamata pelindung.',
                'control_hierarchical_id' => 5,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 5,
                'risk_control' => 'Penyediaan tempat teduh.& Fasilitas Air Minum.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 5,
                'risk_control' => 'Pengaturan waktu kerja untuk menghindari paparan panas ekstrem.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 6,
                'risk_control' => 'Ventilasi yang baik di area kerja.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 6,
                'risk_control' => 'Penggunaan masker pelindung.',
                'control_hierarchical_id' => 5,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 7,
                'risk_control' => 'Fasilitas P3K',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 7,
                'risk_control' => 'Penggunaan sarung tangan pelindung.',
                'control_hierarchical_id' => 5,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 8,
                'risk_control' => 'Fasilitas meja kerja dengan ketinggian yang dapat disesuaikan.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 8,
                'risk_control' => 'Pelatihan sitem kerja (posisi pekerja) yang benar.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 9,
                'risk_control' => 'Inspeksi alat secara berkala.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 9,
                'risk_control' => 'Penggunaan sarung tangan sebagai pelindung.',
                'control_hierarchical_id' => 5,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 10,
                'risk_control' => 'Pengaturan waktu kerja dengan istirahat teratur.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 10,
                'risk_control' => 'Pelatihan teknik anyaman yang ergonomis.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 11,
                'risk_control' => 'Fasilitas kursi atau meja yang ergonomis.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 11,
                'risk_control' => 'Pelatihan postur yang baik saat bekerja.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 12,
                'risk_control' => 'Ventilasi yang baik di area kerja.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 12,
                'risk_control' => 'Penggunaan masker atau respirator.',
                'control_hierarchical_id' => 5,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 13,
                'risk_control' => 'Penyimpanan bahan kimia jauh dari sumber api.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 13,
                'risk_control' => 'Pemasangan alat pemadam kebakaran (APAR) di area kerja.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 14,
                'risk_control' => 'Penggunaan alat uji stabilitas yang aman dan berstandar',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 14,
                'risk_control' => 'Pelatihan teknis uji stabilitas.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 15,
                'risk_control' => 'Penyediaan kursi kerja yang dapat disesuaikan.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 15,
                'risk_control' => 'Pelatihan postur tubuh yang baik saat bekerja.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 16,
                'risk_control' => 'Penggunaan alat pemotong yang aman dan bestandar.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 16,
                'risk_control' => 'Pelatihan penggunaan alat pengemas.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 17,
                'risk_control' => 'Penggunaan alat bantu angkat atau forklift.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 17,
                'risk_control' => 'Pelatihan teknik angkat yang benar.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 18,
                'risk_control' => 'Penggunaan alat bantu angkat.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 18,
                'risk_control' => 'Pelatihan teknik angkat yang benar.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 19,
                'risk_control' => 'Penyediaan jalur yang aman dan bebas hambatan.',
                'control_hierarchical_id' => 3,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'risk_assessment_id' => 19,
                'risk_control' => 'Pencahayaan yang baik di area kerja.',
                'control_hierarchical_id' => 4,
                'cost' => 100000,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
