<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RiskAssessmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('risk_assessments')->insert([
            [
                'hazard_identification_id' => 1,
                'likelihood' => 3,
                'severity' => 4,
                'total' => 12,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 2,
                'likelihood' => 4,
                'severity' => 2,
                'total' => 8,
                'category' => 'Moderat',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 3,
                'likelihood' => 3,
                'severity' => 4,
                'total' => 12,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 4,
                'likelihood' => 2,
                'severity' => 5,
                'total' => 10,
                'category' => 'Ekstrem',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 5,
                'likelihood' => 2,
                'severity' => 4,
                'total' => 8,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 6,
                'likelihood' => 3,
                'severity' => 3,
                'total' => 9,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 7,
                'likelihood' => 3,
                'severity' => 3,
                'total' => 9,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 8,
                'likelihood' => 3,
                'severity' => 4,
                'total' => 12,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 9,
                'likelihood' => 4,
                'severity' => 3,
                'total' => 12,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 10,
                'likelihood' => 3,
                'severity' => 3,
                'total' => 9,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 11,
                'likelihood' => 3,
                'severity' => 3,
                'total' => 9,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 12,
                'likelihood' => 3,
                'severity' => 4,
                'total' => 12,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 13,
                'likelihood' => 2,
                'severity' => 5,
                'total' => 10,
                'category' => 'Ekstrem',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 14,
                'likelihood' => 3,
                'severity' => 3,
                'total' => 9,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 15,
                'likelihood' => 3,
                'severity' => 3,
                'total' => 9,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 16,
                'likelihood' => 3,
                'severity' => 2,
                'total' => 6,
                'category' => 'Moderat',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 17,
                'likelihood' => 3,
                'severity' => 3,
                'total' => 9,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 18,
                'likelihood' => 3,
                'severity' => 3,
                'total' => 9,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'hazard_identification_id' => 19,
                'likelihood' => 2,
                'severity' => 4,
                'total' => 8,
                'category' => 'Tinggi',
                'status' => 'plan',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
